# Generated by Django 3.1.1 on 2020-10-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
