# Generated by Django 3.1.1 on 2020-10-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='last_name',
            new_name='name',
        ),
    ]
