# Generated by Django 3.1.3 on 2020-11-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_auto_20201129_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
