# Generated by Django 3.1.3 on 2020-11-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_auto_20201129_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone_no',
        ),
    ]
