# Generated by Django 3.1.3 on 2020-11-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_auto_20201129_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='number',
        ),
    ]
