# Generated by Django 3.1.3 on 2020-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_auto_20201129_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='number',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
    ]
