# Generated by Django 3.1.3 on 2020-11-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0021_orders_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
    ]
