# Generated by Django 3.1.3 on 2020-11-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0022_remove_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
